package com.amosh.remote.model

data class ComicsListResults(
    val id: String? = null,
    val digitalId: String? = null,
    val title: String? = null,
    val issueNumber: String? = null,
    val variantDescription: String? = null,
    val description: String? = null,
    val modified: String? = null,
    val isbn: String? = null,
    val upc: String? = null,
    val diamondCode: String? = null,
    val ean: String? = null,
    val issn: String? = null,
    val format: String? = null,
    val pageCount: String? = null,
    val textObjects: List<TextObjects>? = null,
    val resourceURI: String? = null,
    val urls: List<Urls>? = null,
    val series: Series? = Series(),
    val variants: List<Variants>? = null,
    val collections: List<Collections>? = null,
    val collectedIssues: List<CollectedIssues>? = null,
    val dates: List<Dates>? = null,
    val prices: List<Prices>? = null,
    val thumbnail: Thumbnail? = Thumbnail(),
    val images: List<Images>? = null,
    val creators: Creators? = Creators(),
    val characters: Characters? = Characters(),
    val stories: Stories? = Stories(),
    val events: Events? = Events(),
)